### ISSUE TITLE
UpdateStack cannot be used with templates containing Transforms.

### ISSUE THREAD

**Issue by ynnr85** [widdix/sqs-lambda-example#1]
Hello, using your example whem I try

`serverless deploy`

I get this error

`UpdateStack cannot be used with templates containing Transforms.`

Please can you help me about it, do you need more information about it?

Thanks for this great code

**Comment by michaelwittig** [comment]
This sounds like you use the serverless framework? Our example uses SAM. 
You should check how to use SAM in Serverless Framework or port the solution to Serverless Framework.
