### ISSUE TITLE
when executing lambda function getting error

### ISSUE THREAD

**Issue by dhipakkumaran** [widdix/sqs-lambda-example#3]
{
  "errorMessage": "Cannot find module 'async'",
  "errorType": "Error",
  "stackTrace": [
    "Object.<anonymous> (/var/task/index.js:4:13)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}

START RequestId: 21691607-7eb7-11e8-83c5-d9463001c266 Version: $LATEST
Unable to import module 'index': Error
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
END RequestId: 21691607-7eb7-11e8-83c5-d9463001c266
REPORT RequestId: 21691607-7eb7-11e8-83c5-d9463001c266	Duration: 0.62 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 33 MB

**Comment by michaelwittig** [comment]
Have you executed `npm install` in the `worker` and `consumer` directory?

**Comment by dhipakkumaran** [comment]
Yes i have executed npm install in both consumer and worker directory. Consumer lambda executed successful and  worker lambda am getting below error.

{
  "errorMessage": "Missing required key 'ReceiptHandle' in params",
  "errorType": "MissingRequiredParameter",
  "stackTrace": [
    "ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)",
    "ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)",
    "ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)",
    "ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)",
    "Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:125:42)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
    "callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:95:12)",
    "/var/task/node_modules/aws-sdk/lib/event_listeners.js:85:9",
    "finish (/var/task/node_modules/aws-sdk/lib/config.js:320:7)",
    "/var/task/node_modules/aws-sdk/lib/config.js:338:9"
  ]
}

**Comment by michaelwittig** [comment]
I don't understand how you can get an error if deployment failed #2 Does not look like you deployed the code as documented.
